library(boot)
library(readr)
library(ggplot)
library(car)

# Core functions for STA380 checkpoint: bootstrap estimation for simple linear regression

# Assign the data from the csv file
data <- read_csv("submission/Basic Implementation/BostonHousing.csv")

# Model setup

#' Generate simple linear regression model
#' @description Help to calculate the OLS estimators generate by using 
#' Boston Housing dataset.
#' @data Boston Housing dataset.
#' @param respond A string contains selecting variable name.
#' @param predictor A string contains selecting variable name.
#' @return A list containing: beta0, beta1, sd and ols confidence interval.
#' @importFrom stats lm
#' @examples 
#' respond <- "MEDV"
#' predictor <-"LSTAT"
#' ols_slr <- ols_estimators(data,respond, predictor)
#' print(ols_slr)
#' @export
ols_estimators<-function(data,respond, predictor){
  #check the data if run correctly
  head(data)
  # Setup the linear regression model
  lr_model <- lm(reformulate(predictor, respond), data = data)
  model_summary <- summary(model)
  std_error = model_summary$coefficients[1,"Std. Error"]
  ols_slr <- list(
    beta0 = coef(model)[1],
    beta1 = coef(model)[2],
    ols_conf_int = confint(model, level = 0.95))
  return(ols_slr)
}

#' Bootstrap Function for Linear Model Coefficients
#' This function is designed to be used with bootstrap methods
#' @description It extracts a bootstrap sample based on the provided indices and 
#' returns the coefficients of a pre-fitted linear model. 
#' @data Boston Housing dataset.
#' @param index A vector of indices generate by boot package
#' @param respond A string contains selecting variable name.
#' @param predictor A string contains selecting variable name.
#' @return A named numeric vector of coefficients from the linear model
#' @importFrom boot boot
#' @example 
#' respond <- "MEDV"
#' predictor <-"LSTAT"
#' boots <- boot_fn(data, index,predictor, respond)
#' head(boots)
#' @export
boot_fn <- function(data, index,predictor, respond){
  d <- data[index, ]
  model <- lm(reformulate(predictor, respond), data = data)
  return(coef(model))
}

#' Bootstrap analysis
#' @description
#' @param data Boston Housoing dataset
#' @param model A linear regression model.
#' @param R Number of bootstrap samples (set as 1000)
#' @param seed Input seed for reproducibility 
#' @param boot_fn generated by boot_fn
#' @return A list containing: Bootstrap bias estimates,standard errors, etc
#' @importFrom boot boot
#' @importForm boot boot.ci
#' @example 
#' respond <- "MEDV"
#' predictor <-"LSTAT"
#' boots <- boot_fn(data, index,predictor, respond)
#' head(boots)
#' boot_result<-bootstrap_slr_summary(data, model= lrmodel, 
#' R = 1000,seed = NULL,boots)
#' print(boot_result)
#' @export
bootstrap_slr_summary <- function(data, model= lrmodel, R = 1000,seed = NULL,
                                  boot_fn){  
  if (!is.null(seed)) {
    set.seed(seed)
  }else{
    set.seed(100)
  }
  boot_model<- boot(data = data,
                    statistic = boot_fn,
                    R = 1000)
  boot_slr < - list(
    boot_b0_star = boot_model$t[,1],
    boot_b1_star = boot_model$t[,2],
    boot_b0_sd = sd(boot_model$t[,1]),
    boot_b1_sd = sd(boot_model$t[,2]),
    boot_b0_bias = boot_model$bias[1],
    boot_b1_bias = boot_model$bias[2],
    boot_b0_ci <- boot.ci(boot_result, index = 1, type = "perc"),
    boot_b1_ci <- boot.ci(boot_result, index = 2, type = "perc"),
  )
  return(boot_slr)
}

# Output Implementation

#' Bootstrap Summary Table
#'@description Calculates descriptive statistics for the selected 
#'numerical variables, including mean, median, standard deviation,etc.
#' @param boot_slr Bootstrap coefficients generate by bootstrap_slr_summary()
#' @param ols_slr OLS's coefficients generate by ols_estimators()
#' @return A data.frame with rows for intercept and slope and columns.
#' @examples
#' 
#' @export
bootstrap_slr <-function(boot_slr,ols_slr){
  ols_b0 <- ols_slr$beta0
  ols_b1 <- ols_slr$beta1
  boot_b0 <- boot_slr$boot_b0_star
  boot_b1 <- boot_slr$boot_b1_star
  boot_mean <- c(intercept = mean(boot_b0), slope = mean(boot_b1))
  boot_se   <- c(intercept = boot_slr$boot_b0_sd, slope = boot_slr$boot_b1_sd)
  bias      <- c(intercept = boot_slr$boot_b0_bias, slope = boot_slr$boot_b1_bias)
  variance  <- boot_se^2
  mse       <- variance + bias^2
  ols_coef<-c(ols_b0, ols_b1)
  data.frame(
    term = c("intercept", "slope"),
    ols = unname(ols_coef),
    boot_mean = unname(boot_mean),
    boot_se = unname(boot_se),
    bias = unname(bias),
    variance = unname(variance),
    mse = unname(mse),
    row.names = NULL
  )
  
}

#' Calculate the correlation coefficient




# Visualization
#' Plot bootstrap histogram with OLS reference line
#' 
#' 
#' Confidence intervals for SLR coefficients (bootstrap percentile + OLS)
#' 
#' 
#' Boxplot: bootstrap percentile CI vs OLS CI
